# Generated by Django 5.2.4 on 2025-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la boutique')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('city', models.CharField(default='Luanda', max_length=100, verbose_name='Ville')),
                ('is_main', models.BooleanField(default=False, verbose_name='Boutique principale')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('is_main',), name='unique_main_boutique')],
            },
        ),
    ]
