# Generated by Django 5.2.4 on 2025-07-25 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='Mois')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Chiffre d'affaires total")),
                ('num_sales', models.PositiveIntegerField(default=0, verbose_name='Nombre de ventes')),
                ('top_selling_products', models.JSONField(blank=True, null=True, verbose_name='Produits les plus vendus')),
                ('low_stock_alerts', models.JSONField(blank=True, null=True, verbose_name='Alertes stock bas')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Généré le')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='monthly_reports/', verbose_name='Fichier du rapport')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='core.boutique', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Rapport Mensuel',
                'verbose_name_plural': 'Rapports Mensuels',
                'ordering': ['-year', '-month'],
                'unique_together': {('boutique', 'month', 'year')},
            },
        ),
    ]
