# Generated by Django 5.1.5 on 2025-08-29 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('daily', 'Journalier'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('annual', 'Annuel')], max_length=20, verbose_name='Type de rapport')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name="Chiffre d'affaires total")),
                ('num_sales', models.PositiveIntegerField(default=0, verbose_name='Nombre de ventes')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Généré le')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.boutique', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.DeleteModel(
            name='RapportMensuel',
        ),
    ]
