# Generated by Django 5.2.4 on 2025-07-25 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de vente')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant total')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.boutique', verbose_name='Boutique')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='users.user', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Fichier PDF')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.vente', verbose_name='Vente associée')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire au moment de la vente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.produit', verbose_name='Produit')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sales.vente', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Ligne de Vente',
                'verbose_name_plural': 'Lignes de Vente',
                'unique_together': {('sale', 'product')},
            },
        ),
    ]
