# Generated by Django 5.2.4 on 2025-08-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_vente_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='notes',
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_vente', to='sales.vente', verbose_name='Vente'),
        ),
    ]
